### ISSUE TITLE
[stable/redis] Incompatible types for equality comparison

### ISSUE THREAD

**Issue by sebnyberg** [helm/charts#18141]
After upgrading to Helm 2.15, the chart (v9.3.2) is throwing an error regarding the EQ operator at
https://github.com/helm/charts/blob/master/stable/redis/templates/redis-master-statefulset.yaml#L81

Error:

```
Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison
```

To try it out, simply run:

```
helm install stable/redis
```

**Comment by nahid** [comment]
Same error:
`error calling eq: incompatible types for comparison`

**Comment by carrodher** [comment]
Hi, a new version of Helm was released yesterday (`2.15.1`). Among other fixes, it includes:
- Reverted changes introduced in https://github.com/helm/helm/pull/6010

Can you confirm if the issue is solved using the new Helm version?

**Comment by tomjohnburton** [comment]
Still unresolved unfortunately.

I ran the update
```
▶ helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```

Followed by attempting to install
```
 helm install stable/redis --values values.yaml --name redis --namespace default                  
Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing 
"redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison

```

**Comment by skotu-vida** [comment]
@tomjohnburton can you paste your values.yaml once

**Comment by skotu-vida** [comment]
@tomjohnburton can you paste your values.yaml once

**Comment by tomjohnburton** [comment]
Hangon! I just realised that I hadn't set the `securityContext` in both the `slave` and `master` configuration.

```
  ## Redis Master Pod Security Context
  ##
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
```
```
  # Redis slave pod Security Context
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
```

**Comment by tomjohnburton** [comment]
New error
```
  Normal   Pulled     15s                kubelet, ip-13-37-3-31.eu-central-1.compute.internal  Container image "docker.io/oliver006/redis_exporter:v0.20.2" already present on machine
  Normal   Created    14s (x2 over 16s)  kubelet, ip-13-37-3-31.eu-central-1.compute.internal  Created container
  Warning  Failed     14s (x2 over 16s)  kubelet, ip-13-37-3-31.eu-central-1.compute.internal  Error: failed to start container "metrics": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
```

**Comment by silvez-dh** [comment]
Same issue for `anchore-engine` on e helm `v2.15.1`

```
  Error: render error in "anchore-engine/templates/engine_configmap.yaml": template: anchore-engine/templates/engine_configmap.yaml:156:15: executing "anchore-engine/templates/engine_configmap.yaml" at <gt .Values.anchoreAnalyzer.layerCacheMaxGigabytes 0.0>: error calling gt: incompatible types for comparison
```

**Comment by carrodher** [comment]
I just tried using Helm 2.15.1 and the issue seems to be solved:
```bash
$ helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```
take into account that Helm is upgraded in both sides, client and server, for that, I downloaded the new Helm version from the [official GH repository](https://github.com/helm/helm/releases/tag/v2.15.1) and install the binary. After that, I upgraded Tiller with `helm init --upgrade`.

Using this new version I installed Redis by running
```bash
$ helm repo update
$ helm install stable/redis
```
and everything works as expected:
```bash
$ kubectl get pods
NAME                                        READY   STATUS              RESTARTS   AGE
funky-sloth-redis-master-0                  1/1     Running            0          10m27s
funky-sloth-redis-slave-0                   1/1     Running            0          10m27s
funky-sloth-redis-slave-1                   1/1     Running            0          10m
```

I think this issue can be considered solved. If you have other unrelated issues or issues with other charts, please, open a new issue to avoid mixing topics.

**Comment by canalptekin** [comment]
Helm init and updated. Problem not solved.

Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

helm install stable/redis --values values.yaml
Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison

**Comment by silvez-dh** [comment]
for me still not solved:

```
helm version                                                                                                                               
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
```
```
helmfile --file kubernetes/helmfiles/ --selector app=anchore-engine diff 
.
.
.
  Error: render error in "anchore-engine/templates/engine_configmap.yaml": template: anchore-engine/templates/engine_configmap.yaml:156:15: executing "anchore-engine/templates/engine_configmap.yaml" at <gt .Values.anchoreAnalyzer.layerCacheMaxGigabytes 0.0>: error calling gt: incompatible types for comparison
  Error: plugin "diff" exited with error
```

anchore-engine `version: 1.3.4`

**Comment by theshizzah** [comment]
I am on helm 2.15.1 and seeing this issue

`
$ helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
$ helm install stable/redis --name redis --set image.tag=5.0.5-debian-9-r104
Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison
`

**Comment by theshizzah** [comment]
Ah, upgraded my helm server to `2.15.1` to match and that seemed to fix it

**Comment by sebnyberg** [comment]
Resolved for me too. Closing issue.

**Comment by evalsocket** [comment]
I am facing same issue with helm 2.16.0

`Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison`

**Comment by carrodher** [comment]
> I am facing same issue with helm 2.16.0
> 
> `Error: render error in "redis/templates/redis-slave-statefulset.yaml": template: redis/templates/redis-slave-statefulset.yaml:87:18: executing "redis/templates/redis-slave-statefulset.yaml" at <eq .Values.securityContext.runAsUser 0.0>: error calling eq: incompatible types for comparison`

Can you run `$ helm version` and paste here the output?

**Comment by patvdleer** [comment]
v3.0.0 seems to have the issue as well https://github.com/helm/helm/issues/7023
